apiVersion: v2
name: delo-openfiber-portal
description: A Helm chart for Kubernetes deployment of the DELOINS OpenFiber portal

maintainers:
- name: Codaxy

type: application
version: 1.0.1
appVersion: "latest"