replicaCount: 1

image:
  repository: ghcr.io/codaxy/delo-openfiber-portal
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets:
  - name: ghcr-regcred

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: "delo-openfiber-portal-sa"

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext:
  capabilities:
    drop:
    - ALL

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: of.127.0.0.1.nip.io
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

# It's better to override resources per environment
resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}

env:
  ASPMETCORE_ENVIRONMENT: Production
  
secretEnv:
  - name: ConnectionStrings__AppDbConnection
    valueFrom:
      secretKeyRef:
        name: delo-of-portal-db-conn
        key: ConnectionStrings__AppDbConnection
  - name: ConnectionStrings__NsoDbConnection
    valueFrom:
      secretKeyRef:
        name: delo-of-portal-db-conn
        key: ConnectionStrings__NsoDbConnection
